Feature/delete downloads
UUDigitalHumanitieslab/I-analyzer pull request #1336
Opened 2023-11-28 10:52 UTC by JeltevanBoheemen

This partially implements #976, only the download part. Even with an expiration period, it's nice to offer a direct way. Creating a PR now because deleting accounts is slightly more involved, and may take some time to get around to for me.

Tried really hard to fit the `delete all` button underneath the `Delete` header, but couldn't get PrimeNG to comply.

2023-11-28 11:22 UTC, lukavdplas requested changes
Nice, very neat! :)

I have one comment re. the interface in the downloads and search history page.

2023-11-28 11:22 UTC, lukavdplas commented on frontend/src/app/history/download-history/download-history.component.html
> +        </ng-template>
I agree this is a good place for a delete button, but it's inconsistent that downloads are deleted here, while queries are deleted from the settings menu. The pages are almost identical, so they should handle this the same way. Perhaps you could move the "delete search history" button?

2023-11-28 11:22 UTC, lukavdplas commented on frontend/src/app/history/download-history/download-history.component.html
> +                </td>
Nice.

Addition my earlier comment: if you choose to make the search history menu more like this page, don't bother adding this action. The search history includes a unique filter, which means deleting one query would usually cause another identical one to appear. A decent delete button per query would take more time.

2024-04-11 09:13 UTC, closed without merging

2024-04-11 09:13 UTC, JeltevanBoheemen commented
Looking at this later!