Feature/euparl
UUDigitalHumanitieslab/I-analyzer pull request #1631
Opened 2024-07-18 12:32 UTC by BeritJanssen

Merge after #1556 : will rebase then to mitigate failing tests.

2024-09-04 08:46 UTC, BeritJanssen commented on backend/corpora/parliament/conftest.py
Applied alphabetical sorting here.

2024-09-25 07:53 UTC, JeltevanBoheemen requested changes
Code is clean. Usage of `rdflib` utilities makes it very readable. Two small requests.

2024-09-25 07:53 UTC, JeltevanBoheemen commented on backend/corpora/parliament/tests/test_import.py
>  CORPUS_TEST_DATA = [
It takes a lot of scrolling to get to the actual tests in this file. I propose making `CORPUS_TEST_DATA` a fixture in a separate file.

2024-09-25 07:53 UTC, JeltevanBoheemen commented on backend/corpora/parliament/utils/field_defaults.py
> +        name="date",
Autoformat I suppose? The rest of the file is in single quotes. Don't really need to revert but pointing out for future reference.

2024-09-25 07:53 UTC, JeltevanBoheemen commented on backend/corpora/parliament/euparl.py
> +            continue
Please add a comment on which cases are being ignored here, preferable with a more specific `Exception`

2024-09-25 13:40 UTC, merged